openapi: 3.0.0
info:
  title: appointment-service
  version: 1.0.0
paths:
  /appointments:
    parameters: [ ]
    post:
      summary: ''
      operationId: createAppointment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppointmentDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentDto'
  /reasons:
    get:
      summary: Your GET endpoint
      tags: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReasonDto'
              examples: { }
      operationId: getReasons
    post:
      summary: ''
      operationId: createReason
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReasonDto'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReasonDto'
components:
  schemas:
    ReasonDto:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        channels:
          type: array
          items:
            type: string
        treatments:
          type: array
          items:
            $ref: '#/components/schemas/TreatmentDto'
    ChannelEnum:
      type: string
      enum:
        - IN_PERSON
        - VIDEO_CALL
    AppointmentDto:
      type: object
      properties:
        id:
          type: string
        channel:
          $ref: '#/components/schemas/ChannelEnum'
        symptoms:
          type: array
          items:
            type: string
        reasonId:
          type: string
        practiceId:
          type: string
        startTime:
          type: string
        endTime:
          type: string
        videoCallLink:
          type: string
        cancellationLink:
          type: string
        notes:
          type: string
    TreatmentDto:
      type: object
      properties:
        staff:
          type: string
        duration:
          type: string
  responses: { }
  requestBodies: { }
